---

language: python

python:
  - 2.7

install:
  - pip install ansible

script:
  - git clone https://github.com/fubarhouse/fubarhouse.npm ../fubarhouse.npm
  - cd tests
  - ansible-playbook -i inventory playbook.yml --syntax-check
  - ansible-playbook -i inventory playbook.yml --sudo -vvvv
