---

- name: "PM2 | Locate local PM2 directory"
  stat:
    path: "{{ fubarhouse_pm2.user_dir }}/.nvm/v{{ item }}/lib/node_modules/pm2"
  register: pm2_local_directory
  with_items:
    - "{{ node_version }}"
    - "{{ node_versions }}"
  when: pm2_install_type != "local" or pm2_clean_install == true

- name: "PM2 | Remove local PM2 directory"
  file:
    path: "{{ item.invocation.module_args.path }}"
    state: absent
  with_items:
    - "{{ pm2_local_directory.results }}"
  when: (item.stat.exists == true and pm2_install_type != "local") or pm2_clean_install == true

- name: "PM2 | Remove global executable"
  become: yes
  become_user: "root"
  file:
    path: "/usr/local/bin/pm2"
    state: absent
    force: yes
  when: pm2_install_type != "global" or pm2_clean_install == true

- name: "PM2 | Remove global installations"
  become: yes
  become_user: root
  file:
    path: "/usr/local/lib/node_modules/{{ item }}"
    state: absent
  with_items:
    - pm2
    - pm2-axon
    - pm2-axon-rpc
    - pm2-deploy
    - pm2-multimeter
  when: pm2_install_type != "global" or pm2_clean_install == true

- name: "PM2 | Flush logs"
  become: yes
  become_user: "{{ fubarhouse_user }}"
  raw: "/usr/local/bin/pm2 flush"
  when: node_apps.0 is defined

- name: "PM2 | Ensure stopped"
  become: yes
  become_user: "{{ fubarhouse_user }}"
  raw: "/usr/local/bin/pm2 stop '{{ item.name }}'"
  with_items: "{{ node_apps }}"
  ignore_errors: yes
  when: node_apps.0 is defined

- name: "PM2 | Remove global executable"
  become: yes
  become_user: "root"
  file:
    path: "/usr/local/bin/pm2"
    state: absent
    force: yes
  when: pm2_install_type != "global" or pm2_clean_install == true