---
# file: roles/fubarhouse.pm2/tasks/main.yml

- name: "Define user variable for ssh use"
  set_fact:
    fubarhouse_user: "{{ ansible_ssh_user }}"
  when: ansible_ssh_user is defined

- name: "Define user variable for non-ssh use"
  set_fact:
    fubarhouse_user: "{{ ansible_user_id }}"
  when: ansible_ssh_user is not defined

- name: "Define user variable for ssh use"
  set_fact:
    fubarhouse_user: "{{ ansible_ssh_user }}"
  when: ansible_ssh_user is defined

- name: "Define user variable for non-ssh use"
  set_fact:
    fubarhouse_user: "{{ ansible_user_id }}"
  when: ansible_ssh_user is not defined

- name: "Define OS-specific variables"
  include_vars: "config-{{ ansible_os_family }}.yml"
  when: fubarhouse_pm2 is not defined

- name: "Set to non-clean install if unset"
  set_fact:
    pm2_clean_install: false
  when: pm2_clean_install is undefined

- name: "Set to global install if unset"
  set_fact:
    pm2_install_type: global
  when: pm2_install_type != "custom" and pm2_custom_path is undefined

- name: "Scanning for Apache2"
  stat:
    path: /usr/sbin/apache2
  register: apache2_isinstalled

- name: "Scanning for Nginx"
  stat:
    path: /usr/sbin/nginx
  register: nginx_isinstalled

- name: "Importing PM2 Tasks"
  include: pm2.yml

- name: "Importing NodeJS Application Tasks"
  include: apps.yml
