---
# file: roles/fubarhouse.pm2/tasks/main.yml

- name: "Importing dependencies"
  include_tasks: depenencies.yml

- name: "Import uninstall tasks"
  include_tasks: uninstall.yml
  when: pm2_clean_install

- name: "Import install Tasks"
  include_tasks: install.yml

- name: "Importing NodeJS Application Tasks"
  include_tasks: applications.yml
  when: node_apps.0 is defined
