---

- name: "PM2 | Define variables"
  become: yes
  become_user: "{{ fubarhouse_user }}"
  set_fact:
    pm2_exec: "{{ fubarhouse_pm2.user_dir }}/.nvm/v{{ node_version }}/bin/pm2"
    node_path: "{{ fubarhouse_pm2.user_dir }}/.nvm/v{{ node_version }}"

- name: "PM2 | Remove global installations"
  become: yes
  become_user: root
  file:
    path: "/usr/local/node_modules/pm2"
    state: absent

- name: "PM2 | Ensure installed"
  become: yes
  become_user: "root"
  npm:
    name: "{{ item }}"
    executable: "{{ fubarhouse_npm.npm_install_exec }}"
    global: yes
    state: latest
  with_items:
    - "pm2"

- name: "PM2 | Remove global executable"
  become: yes
  become_user: "root"
  file:
    path: "/usr/local/bin/pm2"
    state: absent
    force: yes