---

# file: roles/fubarhouse.pm2/tasks/pm2.yml

- name: "PM2 | Locate NPM"
  shell: which npm | cat
  register: which_npm

- name: "Include cleanup tasks"
  include: cleanup.yml
  when: pm2_clean_install

- name: "PM2 | Ensure installed (global)"
  become: yes
  become_user: root
  npm:
    name: "pm2"
    executable: "{{ which_npm.stdout }}"
    state: latest
    path: "/usr/local/lib"
  when: pm2_install_type == "global"

- name: "PM2 | Symlink global install"
  file:
    src: /usr/local/lib/node_modules/pm2/bin/pm2
    dest: /usr/local/bin/pm2
    state: link
  when: pm2_install_type == "global"

- name: "PM2 | Ensure installed (local)"
  become: yes
  become_user: "root"
  npm:
    name: "pm2"
    executable: "{{ which_npm.stdout }}"
    state: latest
    path: "{{ fubarhouse_pm2.user_dir }}/.nvm/v{{ node_version }}/lib"
  when: pm2_install_type == "local"

- name: "PM2 | Symlink local install"
  file:
    src: "{{ fubarhouse_pm2.user_dir }}/.nvm/v{{ node_version }}/lib/node_modules/pm2/bin/pm2"
    dest: /usr/local/bin/pm2
    state: link
  when: pm2_install_type == "local"

- name: "PM2 | Ensure installed (custom)"
  become: yes
  become_user: "root"
  npm:
    name: "pm2"
    executable: "{{ which_npm.stdout }}"
    path: "{{ pm2_custom_path }}"
    state: latest
  when: pm2_install_type == "custom"

- name: "PM2 | Symlink custom install"
  file:
    src: "{{ pm2_custom_path }}/node_modules/pm2/bin/pm2"
    dest: /usr/local/bin/pm2
    state: link
  when: pm2_install_type == "custom"

- name: "PM2 | Run PM2"
  shell: /usr/local/bin/pm2 list
  register: pm2_verify

- name: "PM2 | Verify installation"
  assert:
    that: '"pm2 show <id|name>" in "{{ pm2_verify.stdout_lines }}"'