---

# file: roles/fubarhouse.pm2/tasks/pm2.yml

- name: "PM2 | Locate NPM"
  shell: which npm | cat
  register: which_npm
  changed_when: false

- name: "Include cleanup tasks"
  include: cleanup.yml
  when: pm2_clean_install

- name: "PM2 | Set paths"
  set_fact:
    pm2_install_path: "/usr/local/lib"
    pm2_sym_path: "/usr/local/lib/node_modules/pm2/bin/pm2"

- name: "PM2 | Install"
  npm:
    name: "pm2"
    executable: "{{ which_npm.stdout }}"
    state: latest
    path: "{{ pm2_install_path }}"
  when: '"npm" not in which_npm.stdout'

- name: "PM2 | Touch"
  stat:
    path: "{{ pm2_sym_path }}"
  changed_when: false
  failed_when: false
  register: pm2_file_check
  when: '"npm" not in which_npm.stdout'

- name: "PM2 | Symlink"
  file:
    src: "{{ pm2_sym_path }}"
    dest: /usr/local/bin/pm2
    state: link
  when: '"npm" not in which_npm.stdout'

- name: "PM2 | Verify installation"
  shell: which pm2
  register: pm2_verify
  changed_when: false
  failed_when: '"pm2" not in pm2_verify.stdout'

