---

# file: roles/fubarhouse.pm2/tasks/pm2.yml

- name: "PM2 | Locate NPM"
  shell: which npm | cat
  register: which_npm
  changed_when: false

- name: "Include cleanup tasks"
  include: cleanup.yml
  when: pm2_clean_install

- name: "PM2 | Locate PM2"
  shell: which pm2 | cat
  register: which_pm2
  changed_when: false

- name: "PM2 | Install"
  npm:
    name: "pm2"
    executable: "{{ which_npm.stdout }}"
    state: latest
    global: yes
  when: '"pm2" not in which_pm2.stdout'

- name: "PM2 | Verify installation"
  shell: which pm2
  register: pm2_verify
  changed_when: false
  failed_when: '"pm2" not in pm2_verify.stdout'

