---

- name: "PM2 | Kill daemon"
  shell: '/usr/local/bin/pm2 kill'
  changed_when: false
  failed_when: false
  when: pm2_clean_install == true

- name: "PM2 | Remove executable"
  file:
    path: "/usr/local/bin/pm2"
    state: absent
    force: yes
  when: pm2_clean_install == true

- name: "PM2 | Remove installations"
  file:
    path: "/usr/local/lib/node_modules/{{ item }}"
    state: absent
  with_items:
    - pm2
    - pm2-axon
    - pm2-axon-rpc
    - pm2-deploy
    - pm2-multimeter
  when: pm2_clean_install == true

- name: "PM2 | Flush logs"
  raw: "/usr/local/bin/pm2 flush"
  when: node_apps.0 is defined

- name: "PM2 | Ensure stopped"
  raw: "/usr/local/bin/pm2 stop '{{ item.name }}'"
  with_items: "{{ node_apps }}"
  ignore_errors: yes
  when: node_apps.0 is defined

- name: "PM2 | Remove executable"
  file:
    path: "/usr/local/bin/pm2"
    state: absent
    force: yes
  when: pm2_clean_install == true