---

# file: roles/fubarhouse.pm2/defaults/main.yml

fubarhouse_pm2:
  user: "{{ fubarhouse_user }}"
  user_dir: "/home/{{ fubarhouse_user }}"
  pm2_exec: "/usr/local/bin/pm2"
  vhost_domain_ext: "loc.gbuild.net"